- name: Backend Playbook
  hosts: localhost
  become: true
  tasks:
    - name: Set_Prompt shell
      ansible.builtin.shell:
        set-prompt backend

    - name: Disable Node Newer Version
      ansible.builtin.shell:
       dnf module disable nodejs -y

    - name: Enable Nodejs Node Newer Version
      ansible.builtin.shell:
        dnf module enable nodejs:20 -y

    - name: install NodeJS
      ansible.builtin.dnf:
          name: nodejs
          state: present

    - name: Add expense User
      ansible.builtin.user:
        name: expense

    - name: Copy backend Service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: remove old existing application directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create new application directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download frontend content online
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: true

    - name: Download Nodejs App dependencies
      community.general.npm:
        path: /app

    - name: install mySql client & Mysql Python Module
      ansible.builtin.dnf:
        name:
        - mysql
        - python3-PyMySQL
        state: present

    - name: Load schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: db_ip

    - name: start backend Service
      ansible.builtin.systemd_service:
        state: restarted
        name: backend.service
        enabled: true
        daemon_reload: true