- name: frontEnd Playbook
  hosts: all
  become: true
  tasks:
    - name: Set_Prompt shell
      ansible.builtin.shell:
        set-prompt frontEnd

    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: copy expense file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: remove old HTML directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create HTML Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download frontend content online
      ansible.builtin.unarchive:
      src: https://expense-artifacts.s3.amazonaws.com/expense.frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: true

    - name: stat nginx Service
      ansible.builtin.systemd_service:
          state: restarted
          name: nginx
          enabled: true



